import { DisasterModule, DisasterType, RegionData } from './types';

export const RANDOM_FACTS = [
    "The Philippines sits on the 'Pacific Ring of Fire', home to 75% of the world's volcanoes.",
    "Bamboos are excellent for housing in earthquake zones because they are flexible and bend without breaking.",
    "Mayon Volcano in Albay is famous for having the world's most perfect cone shape.",
    "The Philippine Trench is one of the deepest points in the world, reaching over 10,000 meters deep.",
    "Mangrove forests can reduce wave height by up to 66%, protecting coastlines from storm surges.",
    "The 'Eye' of a typhoon is calm, but the 'Eyewall' surrounding it carries the strongest winds.",
    "Taal Volcano is a 'volcano within a lake, within a volcano, within a lake'.",
    "If the water on a beach suddenly recedes far back, run to high ground immediately—a tsunami may be coming.",
    "The Philippines discovers about 18-20 typhoons entering its Area of Responsibility every year.",
    "Liquefaction can make solid ground behave like quicksand during strong earthquakes."
];

export const MODULES: DisasterModule[] = [
  {
    id: 'mod_eq',
    type: DisasterType.Earthquake,
    title: 'Earthquake & Tsunami',
    description: 'Tectonic shifts, liquefaction, and seismic waves.',
    icon: '🏚️🌊', 
    color: 'bg-orange-500',
    learningContent: `### The Science of Tectonics
The Philippines is a geological hotbed located at the collision zone of the **Eurasian Plate** (subducting under Luzon) and the **Philippine Sea Plate** (subducting at the Philippine Trench). This squeezing action creates the **Philippine Fault Zone (PFZ)**, a 1,200km crack splitting the archipelago from Luzon to Mindanao.

### Seismic Mechanics
* **Hypocenter vs Epicenter**: The hypocenter is the point *inside* the earth where the rupture starts. The epicenter is the point directly above it on the surface.
* **Magnitude (Energy)**: Measured on the Moment Magnitude Scale (Mw). A magnitude 7.0 releases 32 times more energy than a 6.0.
* **Intensity (Shaking)**: Measured by PEIS (I to X). Level VIII is "Very Destructive" where heavy objects overturn and liquefaction is widespread.

### Tsunami Physics
Tsunamis are generated by vertical displacement of the seabed.
* **Speed**: In the deep ocean, they travel at 800 kph (speed of a jet).
* **Shoaling**: As the wave hits shallow coastal water, friction slows the bottom part, causing the top to pile up and rise dramatically, sometimes reaching 30 meters.
* **Drawback**: The trough of the wave often hits first, causing the sea to recede rapidly—a critical natural warning.

### Structural Engineering & Safety
* **Shear Walls**: Reinforced concrete walls that resist horizontal forces.
* **Base Isolation**: Giant rubber bearings that separate the building from the ground, allowing it to "glide" during shaking.
* **The "Soft Story" Flaw**: Buildings with open ground floors (like parking garages) are prone to collapse because they lack shear strength at the base.

### Agriculture & Food Security
* **Irrigation Collapse**: Earthquakes often rupture concrete irrigation canals. Farmers must have contingency plans for manual watering or drought-resistant crops.
* **Saltwater Intrusion**: Land subsidence (sinking) along the coast can allow seawater to invade aquifers and rice paddies, permanently damaging soil fertility.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is the "Drop, Cover, and Hold On" method primarily designed to protect you from?',
        choices: ['Floodwaters', 'Falling debris and structural collapse', 'Fire and smoke', 'High winds'],
        correctIndex: 1,
        explanation: 'The primary goal is to protect your vital organs (head and neck) from falling objects, which are the leading cause of injury in earthquakes.'
      },
      {
        id: 'q2',
        question: 'If you are near the coast and feel a strong earthquake, what should you do immediately?',
        choices: ['Wait for an official warning', 'Go to the beach to check the water level', 'Evacuate to higher ground immediately', 'Call the police'],
        correctIndex: 2,
        explanation: 'Natural signs like strong shaking are your first warning. Do not wait for sirens; tsunamis can arrive in minutes.'
      },
      {
        id: 'q3',
        question: 'Which wave type arrives first during an earthquake?',
        choices: ['S-wave', 'Surface wave', 'P-wave', 'Tidal wave'],
        correctIndex: 2,
        explanation: 'Primary (P) waves travel fastest and are the first to be recorded by seismographs.'
      },
      {
        id: 'q4',
        question: 'What is the difference between Magnitude and Intensity?',
        choices: ['Same thing', 'Magnitude = Energy; Intensity = Shaking Felt', 'Intensity = Energy; Magnitude = Shaking Felt', 'Magnitude is for water; Intensity is for land'],
        correctIndex: 1,
        explanation: 'Magnitude is a fixed number denoting energy. Intensity varies by location based on how the shaking is perceived and the damage caused.'
      },
      {
        id: 'q5',
        question: 'Which phenomenon causes solid ground to behave like a liquid?',
        choices: ['Sublimation', 'Liquefaction', 'Condensation', 'Erosion'],
        correctIndex: 1,
        explanation: 'Liquefaction happens when water-saturated soil loses strength during shaking, often causing buildings to sink or tilt.'
      },
      {
        id: 'q6',
        question: 'What is the Philippine scale used to measure Earthquake Intensity?',
        choices: ['Richter Scale', 'Mercalli Scale', 'PEIS (PHIVOLCS Earthquake Intensity Scale)', 'Fujita Scale'],
        correctIndex: 2,
        explanation: 'PEIS is the specific scale used by PHIVOLCS to describe earthquake effects in the Philippines.'
      },
      {
        id: 'q7',
        question: 'Why is the "Triangle of Life" theory generally not recommended by official agencies?',
        choices: ['It is too hard to explain', 'It relies on buildings collapsing in a specific way that is unpredictable', 'It only works for wood houses', 'It is safer than tables'],
        correctIndex: 1,
        explanation: 'The "Triangle of Life" assumes total pancake collapse. In modern buildings, getting under a table offers guaranteed protection from falling debris, which is more common.'
      },
      {
        id: 'q8',
        question: 'How can earthquakes permanently damage agriculture in coastal areas?',
        choices: ['By scaring the animals', 'By shaking fruit off trees', 'Through subsidence causing saltwater intrusion', 'By heating the soil'],
        correctIndex: 2,
        explanation: 'Land subsidence (sinking) can bring farmland below sea level, leading to saltwater flooding that kills crops.'
      },
      {
        id: 'q9',
        question: 'The "Big One" in Metro Manila refers to a potential rupture of which fault system?',
        choices: ['San Andreas Fault', 'West Valley Fault', 'Philippine Fault Zone', 'Manila Trench'],
        correctIndex: 1,
        explanation: 'The West Valley Fault traverses Metro Manila and nearby provinces and is capable of generating a Magnitude 7.2 earthquake.'
      },
      {
        id: 'q10',
        question: 'What is a "Trench"?',
        choices: ['A deep valley on a mountain', 'A long, narrow depression on the sea floor where subduction occurs', 'A river bed', 'A type of cloud'],
        correctIndex: 1,
        explanation: 'Trenches, like the Philippine Trench, are subduction zones where one tectonic plate dives under another, often generating powerful earthquakes.'
      }
    ]
  },
  {
    id: 'mod_ty',
    type: DisasterType.Typhoon,
    title: 'Typhoon & Flooding',
    description: 'Meteorology, Coriolis effect, and agricultural resilience.',
    icon: '🌀',
    color: 'bg-blue-500',
    learningContent: `### Meteorology: Anatomy of a Storm
Tropical cyclones (Bagyo) form over warm ocean waters (>26.5°C). 
* **Coriolis Effect**: The rotation of the Earth causes storms to spin counter-clockwise in the Northern Hemisphere. This is why typhoons generally move West-Northwest in the Philippines.
* **The Eye**: The center is calm with sinking air.
* **Eyewall**: The ring surrounding the eye has the strongest winds and heaviest rain.
* **Rainbands**: Spiral bands of clouds that bring rain and tornadoes far from the center.

### Classification (PAGASA)
* **Tropical Depression**: Up to 61 kph.
* **Tropical Storm**: 62-88 kph.
* **Severe Tropical Storm**: 89-117 kph.
* **Typhoon**: 118-184 kph.
* **Super Typhoon**: >185 kph.

### Agriculture: Crop Resilience
Typhoons are the most destructive hazard to Philippine agriculture.
* **Mitigation**: Planting wind-break trees, harvesting early when warnings are raised (early warning action), and using flood-tolerant rice varieties (submergence-tolerant).
* **Fisheries**: Fish cages must be lowered or secured. Fishponds often overflow, causing massive stock loss.

### Hydrology: Flooding
* **Flash Floods**: Occur within 6 hours of rain. Common in mountainous areas (CAR, Rizal) where steep slopes channel water rapidly.
* **Riverine Floods**: Gradual rise of water in major basins (Cagayan, Pampanga, Agusan). Can last for weeks.
* **Urban Flooding**: Caused by clogged drainage and concrete surfaces preventing soil absorption.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is the minimum wind speed for a cyclone to be classified as a "Super Typhoon" by PAGASA?',
        choices: ['150 kph', '185 kph', '220 kph', '300 kph'],
        correctIndex: 1,
        explanation: 'PAGASA updated its classification; a Super Typhoon has maximum sustained winds of more than 185 kph.'
      },
      {
        id: 'q2',
        question: 'Which part of a typhoon contains the strongest winds?',
        choices: ['The Eye', 'The Eyewall', 'The Outer Rainbands', 'The Tail'],
        correctIndex: 1,
        explanation: 'The eyewall is the ring of towering thunderstorms surrounding the eye where the most severe weather occurs.'
      },
      {
        id: 'q3',
        question: 'What effect causes typhoons to spin counter-clockwise in the Northern Hemisphere?',
        choices: ['Doppler Effect', 'Butterfly Effect', 'Coriolis Effect', 'Greenhouse Effect'],
        correctIndex: 2,
        explanation: 'The Coriolis Effect, caused by Earth\'s rotation, deflects moving air to the right in the Northern Hemisphere, creating the spin.'
      },
      {
        id: 'q4',
        question: 'What color Rainfall Warning indicates "Evacuation"?',
        choices: ['Yellow', 'Green', 'Orange', 'Red'],
        correctIndex: 3,
        explanation: 'Red Warning means torrential rainfall (>30mm/hr), serious flooding is expected, and evacuation is often required.'
      },
      {
        id: 'q5',
        question: 'Which rice variety characteristic is most useful in flood-prone areas?',
        choices: ['Drought-tolerant', 'Submergence-tolerant', 'Insect-resistant', 'Tall stalks'],
        correctIndex: 1,
        explanation: 'Submergence-tolerant rice (like "Scuba rice") can survive being underwater for up to two weeks.'
      }
    ]
  },
  {
    id: 'mod_vol',
    type: DisasterType.Volcano,
    title: 'Volcanic Eruption',
    description: 'Geothermal energy, ash chemistry, and lahar flows.',
    icon: '🌋',
    color: 'bg-red-600',
    learningContent: `### Geology: Types of Eruptions
* **Phreatic**: Steam-driven explosions caused by water heating up (e.g., Taal 2020 initial blast).
* **Magmatic**: Explosive release of gas and magma.
* **Plinian**: The most violent type, creating massive columns of gas and ash into the stratosphere (e.g., Pinatubo 1991).

### Volcanic Hazards
* **Pyroclastic Flow**: Superheated gas and rock racing down slopes at >80 kph. Impossible to outrun.
* **Lahar**: Volcanic mudflows. Rain mobilizes old ash deposits, creating concrete-like destruction.
* **Vog (Volcanic Smog)**: Sulfur dioxide (SO2) reacting with sunlight and moisture. Hazardous to lungs.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is a "Phreatic" eruption?',
        choices: ['Magma-driven', 'Steam-driven', 'Lava flow only', 'Invisible eruption'],
        correctIndex: 1,
        explanation: 'Phreatic eruptions occur when groundwater is heated by magma, flashing to steam and causing an explosion without necessarily ejecting fresh magma.'
      },
      {
        id: 'q2',
        question: 'What is the most deadly hazard of a volcano, consisting of superheated gas and rocks?',
        choices: ['Lava flow', 'Pyroclastic Flow', 'Ashfall', 'Earthquake'],
        correctIndex: 1,
        explanation: 'Pyroclastic flows travel at high speeds and high temperatures, destroying everything in their path. You cannot outrun them.'
      }
    ]
  },
  {
    id: 'mod_ls',
    type: DisasterType.Landslide,
    title: 'Landslide',
    description: 'Geomorphology, shear stress, and slope stabilization.',
    icon: '⛰️',
    color: 'bg-yellow-700',
    learningContent: `### Geomorphology: Why Slopes Fail
A landslide occurs when the **Shear Stress** (gravity pulling soil down) exceeds the **Shear Strength** (friction and cohesion holding it in place).
* **Triggers**: Heavy rain (increases weight, decreases friction), Earthquakes (shaking loosens bond), or Excavation (removing support).
* **Soil Saturation**: Water fills the gaps between soil particles (pore pressure), pushing them apart and turning the slope into a slurry.

### Warning Signs
* **Drunken Forests**: Trees tilting at odd angles.
* **Cracks**: New cracks in foundations, roads, or soil.
* **Springs**: New water seeps appearing on slopes.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What happens to soil physics when it becomes saturated with water?',
        choices: ['It becomes stronger', 'Pore water pressure increases, reducing friction', 'It becomes lighter', 'It turns into rock'],
        correctIndex: 1,
        explanation: 'Water lubricates the soil particles and pushes them apart (buoyancy), drastically reducing the friction that holds the slope together.'
      },
      {
        id: 'q2',
        question: 'What does the term "Drunken Forest" indicate?',
        choices: ['Trees fermenting fruit', 'Trees tilting due to slow ground movement (creep)', 'A forest with no leaves', 'Trees struck by lightning'],
        correctIndex: 1,
        explanation: 'Tilting trees indicate that the ground beneath them is slowly shifting or creeping downslope.'
      }
    ]
  },
  {
    id: 'mod_ss',
    type: DisasterType.StormSurge,
    title: 'Storm Surge',
    description: 'Oceanography, bathymetry, and coastal defense.',
    icon: '🌊',
    color: 'bg-teal-600',
    learningContent: `### Oceanography: Mechanics of a Surge
A storm surge is NOT a tsunami. It is driven by wind.
* **Wind Setup**: Strong winds push water toward the shore.
* **Pressure Setup**: Low pressure in the eye of the storm allows the ocean surface to rise slightly (inverse barometer effect), though wind is the main driver.
* **Bathymetry**: Shallow, gently sloping continental shelves (like Leyte Gulf) allow water to pile up higher than deep, steep coasts.`,
    quizItems: [
        {
        id: 'q1',
        question: 'Which factor contributes MOST to the height of a storm surge?',
        choices: ['Low pressure', 'Strong winds pushing water', 'Heavy rain', 'Earth rotation'],
        correctIndex: 1,
        explanation: 'While low pressure helps, the sheer force of wind piling water up against the coast is the dominant factor.'
      }
    ]
  },
  {
    id: 'mod_ind',
    type: DisasterType.Industrial,
    title: 'Industrial Hazards',
    description: 'Toxicology, chemical safety, and fire dynamics.',
    icon: '🏭',
    color: 'bg-gray-600',
    learningContent: `### Chemical Safety
* **GHS Symbols**: The Globally Harmonized System uses diamond symbols. 
    * *Flammable* (Fire)
    * *Corrosive* (Test tubes pouring on hand/metal)
    * *Health Hazard* (Person with star on chest - carcinogens).
* **SDS (Safety Data Sheet)**: The 16-section document that MUST be available for every chemical. It lists First Aid, Firefighting, and Handling.`,
    quizItems: [
        {
        id: 'q1',
        question: 'What does the GHS symbol of a "Silhouette of a person with a star on their chest" mean?',
        choices: ['Super hero', 'Health Hazard (Carcinogen/Mutagen)', 'Explosive', 'Radioactive'],
        correctIndex: 1,
        explanation: 'This symbol indicates serious long-term health hazards like cancer, respiratory sensitization, or reproductive toxicity.'
      }
    ]
  },
  {
    id: 'mod_epi',
    type: DisasterType.Epidemic,
    title: 'Epidemics',
    description: 'Virology, immunology, and public health.',
    icon: '🦠',
    color: 'bg-green-600',
    learningContent: `### Biology: The Enemy
* **Virus**: A genetic code (DNA/RNA) inside a protein shell. It cannot reproduce on its own; it hijacks host cells. (e.g., Dengue, COVID-19).
* **Bacteria**: Single-celled organisms. Some are helpful, some cause disease (e.g., Leptospirosis). Treated with antibiotics.
* **Vector**: An organism (mosquito, rat) that transmits the pathogen.`,
    quizItems: [
        {
        id: 'q1',
        question: 'What is "R-naught" (R0) in epidemiology?',
        choices: ['The number of recoveries', 'The basic reproduction number (how many people one case infects)', 'The death rate', 'The number of hospitals'],
        correctIndex: 1,
        explanation: 'R0 indicates the contagiousness of a pathogen. If R0 is 3, one person infects 3 others on average.'
      }
    ]
  }
];

export const PH_REGIONS: RegionData[] = [
    { 
        id: 'NCR', 
        name: 'NCR (Metro Manila)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Typhoon, DisasterType.Epidemic], 
        info: '• **Seismic Risk**: The West Valley Fault runs directly through Marikina, Pasig, and Taguig. A M7.2 earthquake could cause severe structural damage. \n• **Urban Flooding**: High concrete coverage prevents water absorption, leading to rapid street flooding. \n• **Density**: 13M+ population makes it a hotspot for viral transmission.' 
    },
    { 
        id: 'CAR', 
        name: 'CAR (Cordillera)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Landslide], 
        info: '• **Topography**: Steep slopes (>50 degrees) are highly unstable during rain. \n• **Hazards**: Halsema Highway is frequently blocked by rockslides. \n• **Agriculture**: Frost damage ("Andap") affects vegetable crops in Benguet during cold months.' 
    },
    { 
        id: 'R1', 
        name: 'Region I (Ilocos)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Earthquake], 
        info: '• **Coastal**: Faces the West Philippine Sea, prone to storm surges. \n• **Seismic**: The Manila Trench offshore poses a tsunami threat. \n• **Agriculture**: Tobacco and garlic crops are vulnerable to excess moisture.' 
    },
    { 
        id: 'R2', 
        name: 'Region II (Cagayan Valley)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.StormSurge], 
        info: '• **Catchment Basin**: The Cagayan River drains water from multiple mountain ranges, causing massive floods (e.g., Ulysses 2020). \n• **Agriculture**: Major corn and rice producer; floods cause billions in losses.' 
    },
    { 
        id: 'R3', 
        name: 'Region III (Central Luzon)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Lahar**: Rain mobilizes old ash deposits from Mt. Pinatubo, clogging river channels. \n• **Food Security**: Known as the "Rice Granary"; typhoons here impact national rice supply.' 
    },
    { 
        id: 'R4A', 
        name: 'Region IV-A (Calabarzon)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Volcano, DisasterType.Earthquake], 
        info: '• **Taal Volcano**: Proximity to the Permanent Danger Zone involves Batangas and Cavite. \n• **Industrial**: High concentration of factories increases chemical hazard risks during earthquakes.' 
    },
    { 
        id: 'R4B', 
        name: 'Region IV-B (Mimaropa)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Landslide], 
        info: '• **Island Hazards**: Oriental Mindoro is prone to flooding; Palawan faces fewer typhoons but has landslide risks in mining areas. \n• **Maritime**: Inter-island travel is frequently suspended during gales.' 
    },
    { 
        id: 'R5', 
        name: 'Region V (Bicol)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Typhoon Pathway**: The first point of contact for many Pacific typhoons. \n• **Volcanism**: Mt. Mayon and Mt. Bulusan are active. Ashfall affects abaca and coconut crops.' 
    },
    { 
        id: 'R6', 
        name: 'Region VI (Western Visayas)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Mt. Kanlaon**: Active volcano on Negros island. \n• **Oil Spill Risk**: Guimaras Strait is a busy shipping lane (e.g., 2006 Solar 1 spill). \n• **Agriculture**: Sugar cane fields are susceptible to wind damage.' 
    },
    { 
        id: 'R7', 
        name: 'Region VII (Central Visayas)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Landslide], 
        info: '• **Bohol Fault**: Source of the 2013 M7.2 Earthquake. \n• **Landslides**: Cebu\'s transcentral highway has steep, limestone slopes prone to slides. \n• **Urban**: Metro Cebu faces severe drainage issues.' 
    },
    { 
        id: 'R8', 
        name: 'Region VIII (Eastern Visayas)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.StormSurge], 
        info: '• **Surge Risk**: Leyte Gulf\'s shape amplifies storm surges (e.g., Yolanda). \n• **Tectonics**: The Philippine Trench runs parallel to the coast, posing high seismic risk.' 
    },
    { 
        id: 'R9', 
        name: 'Region IX (Zamboanga)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.StormSurge, DisasterType.Earthquake], 
        info: '• **Tsunami History**: The 1976 Moro Gulf earthquake caused a devastating tsunami here. \n• **Flooding**: Zamboanga City lowlands are prone to flash floods.' 
    },
    { 
        id: 'R10', 
        name: 'Region X (Northern Mindanao)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon], 
        info: '• **Flash Floods**: Deforestation in uplands exacerbates runoff, as seen in TS Sendong (2011) in Cagayan de Oro and Iligan.' 
    },
    { 
        id: 'R11', 
        name: 'Region XI (Davao)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Landslide], 
        info: '• **Seismic Swarms**: Series of strong quakes occurred in 2019. \n• **Mining**: Compostela Valley (Davao de Oro) has very high landslide susceptibility due to mining tunnels.' 
    },
    { 
        id: 'R12', 
        name: 'Region XII (Soccsksargen)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Typhoon], 
        info: '• **Cotabato Trench**: A major subduction zone. \n• **Flood Plains**: The Ligawasan Marsh can overflow, affecting North Cotabato and Maguindanao areas.' 
    },
    { 
        id: 'R13', 
        name: 'Region XIII (Caraga)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Landslide], 
        info: '• **Mining Capital**: Surigao del Norte/Sur has extensive nickel mining, loosening soil. \n• **Deep Trench**: Proximity to the Philippine Trench makes it a seismic hotspot.' 
    },
    { 
        id: 'BARMM', 
        name: 'BARMM', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Epidemic], 
        info: '• **Complex Emergency**: Conflict often hampers disaster response and aid delivery. \n• **Tsunami**: The Celebes Sea poses a threat to coastal communities in Sulu and Tawi-Tawi.' 
    }
];
