import { DisasterModule, DisasterType, RegionData, Rank, Achievement, CosmeticItem } from './types';

export const RANKS: Rank[] = [
    { id: 'r1', name: 'Civilian', minXp: 0, icon: '🧍' },
    { id: 'r2', name: 'Trainee', minXp: 500, icon: '📝' },
    { id: 'r3', name: 'Rescuer', minXp: 1500, icon: '⛑️' },
    { id: 'r4', name: 'Responder', minXp: 3000, icon: '🚑' },
    { id: 'r5', name: 'Specialist', minXp: 6000, icon: '🔬' },
    { id: 'r6', name: 'Expert', minXp: 10000, icon: '🎓' },
    { id: 'r7', name: 'Commander', minXp: 20000, icon: '🎖️' },
    { id: 'r8', name: 'National Hero', minXp: 50000, icon: '🦸' },
];

export const AVATARS: CosmeticItem[] = [
    { id: 'av_default', type: 'avatar', content: '🙂', name: 'Default', unlockDesc: 'Unlocked by default' },
    { id: 'av_scout', type: 'avatar', content: '🔭', name: 'The Scout', unlockDesc: 'Read 3 Modules' },
    { id: 'av_brain', type: 'avatar', content: '🧠', name: 'Big Brain', unlockDesc: 'Win 5 Quizzes' },
    { id: 'av_flash', type: 'avatar', content: '⚡', name: 'Speedster', unlockDesc: 'Answer avg < 5s' },
    { id: 'av_veteran', type: 'avatar', content: '🧔', name: 'Veteran', unlockDesc: 'Reach Specialist Rank' },
    { id: 'av_hero', type: 'avatar', content: '🦸', name: 'The Hero', unlockDesc: 'Reach National Hero Rank' },
    { id: 'av_nerd', type: 'avatar', content: '🤓', name: 'Bookworm', unlockDesc: 'Read ALL Modules' },
];

export const BORDERS: CosmeticItem[] = [
    { id: 'bd_none', type: 'border', content: 'border-gray-200', name: 'None', unlockDesc: 'Default' },
    { id: 'bd_green', type: 'border', content: 'border-green-500 ring-4 ring-green-200', name: 'Eco Warrior', unlockDesc: 'Clear Epidemic Module' },
    { id: 'bd_gold', type: 'border', content: 'border-yellow-400 ring-4 ring-yellow-200 shadow-xl', name: 'Champion', unlockDesc: 'Reach Expert Rank' },
    { id: 'bd_fire', type: 'border', content: 'border-red-500 ring-4 ring-orange-400 animate-pulse', name: 'Blaze', unlockDesc: 'Maintain a 7-day streak' },
    { id: 'bd_ice', type: 'border', content: 'border-cyan-400 ring-4 ring-cyan-200', name: 'Cool', unlockDesc: 'Play for 5 hours total' },
];

export const RANDOM_FACTS = [
    "The Philippines sits on the 'Pacific Ring of Fire', home to 75% of the world's volcanoes.",
    "Bamboos are excellent for housing in earthquake zones because they are flexible and bend without breaking.",
    "Mayon Volcano in Albay is famous for having the world's most perfect cone shape.",
    "The Philippine Trench is one of the deepest points in the world, reaching over 10,000 meters deep.",
    "Mangrove forests can reduce wave height by up to 66%, protecting coastlines from storm surges.",
    "The 'Eye' of a typhoon is calm, but the 'Eyewall' surrounding it carries the strongest winds.",
    "Taal Volcano is a 'volcano within a lake, within a volcano, within a lake'.",
    "If the water on a beach suddenly recedes far back, run to high ground immediately—a tsunami may be coming.",
    "The Philippines discovers about 18-20 typhoons entering its Area of Responsibility every year.",
    "Liquefaction can make solid ground behave like quicksand during strong earthquakes."
];

export const MODULES: DisasterModule[] = [
  {
    id: 'mod_eq',
    type: DisasterType.Earthquake,
    title: 'Earthquake & Tsunami',
    description: 'Tectonic shifts, liquefaction, and seismic waves.',
    icon: '🏚️🌊', 
    color: 'bg-orange-500',
    learningContent: `### The Science of Tectonics
The Philippines is a geological hotbed located at the collision zone of the **Eurasian Plate** (subducting under Luzon) and the **Philippine Sea Plate** (subducting at the Philippine Trench). This squeezing action creates the **Philippine Fault Zone (PFZ)**, a 1,200km crack splitting the archipelago from Luzon to Mindanao.

### Seismic Mechanics
* **Hypocenter vs Epicenter**: The hypocenter is the point *inside* the earth where the rupture starts. The epicenter is the point directly above it on the surface.
* **Magnitude (Energy)**: Measured on the Moment Magnitude Scale (Mw). A magnitude 7.0 releases 32 times more energy than a 6.0.
* **Intensity (Shaking)**: Measured by PEIS (I to X). Level VIII is "Very Destructive" where heavy objects overturn and liquefaction is widespread.

### Tsunami Physics
Tsunamis are generated by vertical displacement of the seabed.
* **Speed**: In the deep ocean, they travel at 800 kph (speed of a jet).
* **Shoaling**: As the wave hits shallow coastal water, friction slows the bottom part, causing the top to pile up and rise dramatically, sometimes reaching 30 meters.
* **Drawback**: The trough of the wave often hits first, causing the sea to recede rapidly—a critical natural warning.

### Structural Engineering & Safety
* **Shear Walls**: Reinforced concrete walls that resist horizontal forces.
* **Base Isolation**: Giant rubber bearings that separate the building from the ground, allowing it to "glide" during shaking.
* **The "Soft Story" Flaw**: Buildings with open ground floors (like parking garages) are prone to collapse because they lack shear strength at the base.

### Agriculture & Food Security
* **Irrigation Collapse**: Earthquakes often rupture concrete irrigation canals. Farmers must have contingency plans for manual watering or drought-resistant crops.
* **Saltwater Intrusion**: Land subsidence (sinking) along the coast can allow seawater to invade aquifers and rice paddies, permanently damaging soil fertility.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is the "Drop, Cover, and Hold On" method primarily designed to protect you from?',
        choices: ['Floodwaters', 'Falling debris and structural collapse', 'Fire and smoke', 'High winds'],
        correctIndex: 1,
        explanation: 'The primary goal is to protect your vital organs (head and neck) from falling objects, which are the leading cause of injury in earthquakes.'
      },
      {
        id: 'q2',
        question: 'If you are near the coast and feel a strong earthquake, what should you do immediately?',
        choices: ['Wait for an official warning', 'Go to the beach to check the water level', 'Evacuate to higher ground immediately', 'Call the police'],
        correctIndex: 2,
        explanation: 'Natural signs like strong shaking are your first warning. Do not wait for sirens; tsunamis can arrive in minutes.'
      },
      {
        id: 'q3',
        question: 'Which wave type arrives first during an earthquake?',
        choices: ['S-wave', 'Surface wave', 'P-wave', 'Tidal wave'],
        correctIndex: 2,
        explanation: 'Primary (P) waves travel fastest and are the first to be recorded by seismographs.'
      },
      {
        id: 'q4',
        question: 'What is the difference between Magnitude and Intensity?',
        choices: ['Same thing', 'Magnitude = Energy; Intensity = Shaking Felt', 'Intensity = Energy; Magnitude = Shaking Felt', 'Magnitude is for water; Intensity is for land'],
        correctIndex: 1,
        explanation: 'Magnitude is a fixed number denoting energy. Intensity varies by location based on how the shaking is perceived and the damage caused.'
      },
      {
        id: 'q5',
        question: 'Which phenomenon causes solid ground to behave like a liquid?',
        choices: ['Sublimation', 'Liquefaction', 'Condensation', 'Erosion'],
        correctIndex: 1,
        explanation: 'Liquefaction happens when water-saturated soil loses strength during shaking, often causing buildings to sink or tilt.'
      },
      {
        id: 'q6',
        question: 'What is the Philippine scale used to measure Earthquake Intensity?',
        choices: ['Richter Scale', 'Mercalli Scale', 'PEIS (PHIVOLCS Earthquake Intensity Scale)', 'Fujita Scale'],
        correctIndex: 2,
        explanation: 'PEIS is the specific scale used by PHIVOLCS to describe earthquake effects in the Philippines.'
      },
      {
        id: 'q7',
        question: 'Why is the "Triangle of Life" theory generally not recommended by official agencies?',
        choices: ['It is too hard to explain', 'It relies on buildings collapsing in a specific way that is unpredictable', 'It only works for wood houses', 'It is safer than tables'],
        correctIndex: 1,
        explanation: 'The "Triangle of Life" assumes total pancake collapse. In modern buildings, getting under a table offers guaranteed protection from falling debris, which is more common.'
      },
      {
        id: 'q8',
        question: 'How can earthquakes permanently damage agriculture in coastal areas?',
        choices: ['By scaring the animals', 'By shaking fruit off trees', 'Through subsidence causing saltwater intrusion', 'By heating the soil'],
        correctIndex: 2,
        explanation: 'Land subsidence (sinking) can bring farmland below sea level, leading to saltwater flooding that kills crops.'
      },
      {
        id: 'q9',
        question: 'The "Big One" in Metro Manila refers to a potential rupture of which fault system?',
        choices: ['San Andreas Fault', 'West Valley Fault', 'Philippine Fault Zone', 'Manila Trench'],
        correctIndex: 1,
        explanation: 'The West Valley Fault traverses Metro Manila and nearby provinces and is capable of generating a Magnitude 7.2 earthquake.'
      },
      {
        id: 'q10',
        question: 'What is a "Trench"?',
        choices: ['A deep valley on a mountain', 'A long, narrow depression on the sea floor where subduction occurs', 'A river bed', 'A type of cloud'],
        correctIndex: 1,
        explanation: 'Trenches, like the Philippine Trench, are subduction zones where one tectonic plate dives under another, often generating powerful earthquakes.'
      },
      {
        id: 'q11',
        question: 'What instrument is used to record earthquake waves?',
        choices: ['Barometer', 'Seismograph', 'Thermometer', 'Anemometer'],
        correctIndex: 1,
        explanation: 'A seismograph records the motion of the ground during an earthquake.'
      },
      {
        id: 'q12',
        question: 'Which of these is a sign of an impending tsunami?',
        choices: ['Clear blue skies', 'Rapid recession of water from the shore', 'Heavy rain', 'Strong winds'],
        correctIndex: 1,
        explanation: 'Water receding rapidly exposes the ocean floor and often precedes the arrival of a tsunami wave.'
      },
      {
        id: 'q13',
        question: 'What is the "Hypocenter" of an earthquake?',
        choices: ['The point on the surface directly above the rupture', 'The point deep underground where the rupture starts', 'The measurement of damage', 'The fault line itself'],
        correctIndex: 1,
        explanation: 'The hypocenter (or focus) is the actual starting point of the earthquake underground. The epicenter is the point on the surface above it.'
      },
      {
        id: 'q14',
        question: 'What causes the majority of injuries during an earthquake?',
        choices: ['The ground opening up', 'Falling objects and glass', 'Panic', 'Tsunamis'],
        correctIndex: 1,
        explanation: 'While tsunamis are deadly, in most inland quakes, falling non-structural elements (lights, glass, cabinets) cause the most injuries.'
      },
      {
        id: 'q15',
        question: 'Base isolation pads are made of what material?',
        choices: ['Concrete', 'Steel', 'Layers of rubber and steel', 'Wood'],
        correctIndex: 2,
        explanation: 'Base isolators use layers of rubber and steel to allow the building to move independently of the ground.'
      },
      {
        id: 'q16',
        question: 'What is "Aftershock"?',
        choices: ['A smaller earthquake following the main shock', 'A medical condition', 'A type of wave', 'The sound of an earthquake'],
        correctIndex: 0,
        explanation: 'Aftershocks are smaller quakes that occur in the same area as the main shock as the crust adjusts to stress.'
      },
      {
        id: 'q17',
        question: 'Which scale measures the TOTAL energy released by an earthquake?',
        choices: ['Mercalli', 'Moment Magnitude Scale (Mw)', 'Richter', 'Kelvin'],
        correctIndex: 1,
        explanation: 'Moment Magnitude (Mw) is the most accurate scale for large earthquakes as it calculates total energy based on fault area and slip.'
      },
      {
        id: 'q18',
        question: 'If you are indoors during an earthquake, where should you NOT go?',
        choices: ['Under a sturdy table', 'Against an interior wall', 'Near windows or mirrors', 'In a corner'],
        correctIndex: 2,
        explanation: 'Glass from windows and mirrors can shatter violently during shaking, causing severe cuts.'
      },
      {
        id: 'q19',
        question: 'How much more energy does a Magnitude 8 release compared to a Magnitude 7?',
        choices: ['10 times', '32 times', '2 times', '100 times'],
        correctIndex: 1,
        explanation: 'The magnitude scale is logarithmic. Each whole number increase represents about 32 times more energy release.'
      },
      {
        id: 'q20',
        question: 'The "Ring of Fire" is located in which ocean?',
        choices: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
        correctIndex: 2,
        explanation: 'The Pacific Ring of Fire is a horseshoe-shaped area where many earthquakes and volcanic eruptions occur.'
      }
    ]
  },
  {
    id: 'mod_ty',
    type: DisasterType.Typhoon,
    title: 'Typhoon & Flooding',
    description: 'Meteorology, Coriolis effect, and agricultural resilience.',
    icon: '🌀',
    color: 'bg-blue-500',
    learningContent: `### Meteorology: Anatomy of a Storm
Tropical cyclones (Bagyo) form over warm ocean waters (>26.5°C). 
* **Coriolis Effect**: The rotation of the Earth causes storms to spin counter-clockwise in the Northern Hemisphere. This is why typhoons generally move West-Northwest in the Philippines.
* **The Eye**: The center is calm with sinking air.
* **Eyewall**: The ring surrounding the eye has the strongest winds and heaviest rain.
* **Rainbands**: Spiral bands of clouds that bring rain and tornadoes far from the center.

### Classification (PAGASA)
* **Tropical Depression**: Up to 61 kph.
* **Tropical Storm**: 62-88 kph.
* **Severe Tropical Storm**: 89-117 kph.
* **Typhoon**: 118-184 kph.
* **Super Typhoon**: >185 kph.

### Agriculture: Crop Resilience
Typhoons are the most destructive hazard to Philippine agriculture.
* **Mitigation**: Planting wind-break trees, harvesting early when warnings are raised (early warning action), and using flood-tolerant rice varieties (submergence-tolerant).
* **Fisheries**: Fish cages must be lowered or secured. Fishponds often overflow, causing massive stock loss.

### Hydrology: Flooding
* **Flash Floods**: Occur within 6 hours of rain. Common in mountainous areas (CAR, Rizal) where steep slopes channel water rapidly.
* **Riverine Floods**: Gradual rise of water in major basins (Cagayan, Pampanga, Agusan). Can last for weeks.
* **Urban Flooding**: Caused by clogged drainage and concrete surfaces preventing soil absorption.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is the minimum wind speed for a cyclone to be classified as a "Super Typhoon" by PAGASA?',
        choices: ['150 kph', '185 kph', '220 kph', '300 kph'],
        correctIndex: 1,
        explanation: 'PAGASA updated its classification; a Super Typhoon has maximum sustained winds of more than 185 kph.'
      },
      {
        id: 'q2',
        question: 'Which part of a typhoon contains the strongest winds?',
        choices: ['The Eye', 'The Eyewall', 'The Outer Rainbands', 'The Tail'],
        correctIndex: 1,
        explanation: 'The eyewall is the ring of towering thunderstorms surrounding the eye where the most severe weather occurs.'
      },
      {
        id: 'q3',
        question: 'What effect causes typhoons to spin counter-clockwise in the Northern Hemisphere?',
        choices: ['Doppler Effect', 'Butterfly Effect', 'Coriolis Effect', 'Greenhouse Effect'],
        correctIndex: 2,
        explanation: 'The Coriolis Effect, caused by Earth\'s rotation, deflects moving air to the right in the Northern Hemisphere, creating the spin.'
      },
      {
        id: 'q4',
        question: 'What color Rainfall Warning indicates "Evacuation"?',
        choices: ['Yellow', 'Green', 'Orange', 'Red'],
        correctIndex: 3,
        explanation: 'Red Warning means torrential rainfall (>30mm/hr), serious flooding is expected, and evacuation is often required.'
      },
      {
        id: 'q5',
        question: 'Which rice variety characteristic is most useful in flood-prone areas?',
        choices: ['Drought-tolerant', 'Submergence-tolerant', 'Insect-resistant', 'Tall stalks'],
        correctIndex: 1,
        explanation: 'Submergence-tolerant rice (like "Scuba rice") can survive being underwater for up to two weeks.'
      },
      {
        id: 'q6',
        question: 'Why do typhoons weaken when they hit land?',
        choices: ['They run out of warm water energy', 'Trees block the wind', 'Buildings stop them', 'The air is too dry'],
        correctIndex: 0,
        explanation: 'Typhoons derive energy from warm ocean water evaporation. Land cuts off this fuel source and introduces friction.'
      },
      {
        id: 'q7',
        question: 'What is a "storm surge"?',
        choices: ['A high tide', 'A tsunami', 'Wind-driven ocean rise usually associated with low pressure', 'Heavy rain at sea'],
        correctIndex: 2,
        explanation: 'Storm surge is the abnormal rise of water generated by a storm, over and above the predicted astronomical tides.'
      },
      {
        id: 'q8',
        question: 'In the acronym PAGASA, what does the first "A" stand for?',
        choices: ['Association', 'Atmospheric', 'Astronomy', 'Administration'],
        correctIndex: 1,
        explanation: 'Philippine Atmospheric, Geophysical and Astronomical Services Administration.'
      },
      {
        id: 'q9',
        question: 'Which region in the Philippines is historically hit by the most typhoons?',
        choices: ['Mindanao', 'Bicol Region and Eastern Visayas', 'Palawan', 'Central Visayas'],
        correctIndex: 1,
        explanation: 'The eastern seaboard (Bicol, Samar, Leyte) faces the Pacific Ocean directly, making it the "typhoon highway".'
      },
      {
        id: 'q10',
        question: 'What should you do if the "Eye" passes over your house?',
        choices: ['Go outside to repair the roof', 'Assume the storm is over', 'Stay inside; winds will return from the opposite direction', 'Open all windows'],
        correctIndex: 2,
        explanation: 'The calm eye is deceptive. The second half of the storm will hit shortly, often with winds from the opposite direction.'
      },
      {
        id: 'q11',
        question: 'What temperature must the ocean be to sustain a typhoon?',
        choices: ['20°C', '26.5°C or higher', '35°C', '15°C'],
        correctIndex: 1,
        explanation: 'Warm water (at least 26.5°C) provides the necessary evaporation and latent heat to fuel the storm.'
      },
      {
        id: 'q12',
        question: 'Which signal number warns of winds greater than 185 kph?',
        choices: ['Signal No. 1', 'Signal No. 3', 'Signal No. 5', 'Signal No. 2'],
        correctIndex: 2,
        explanation: 'Signal No. 5 is the highest warning level, used for Super Typhoons with very destructive winds.'
      },
      {
        id: 'q13',
        question: 'Flash floods are most dangerous in which terrain?',
        choices: ['Flat plains', 'Mountainous areas with rivers', 'Coastal beaches', 'Deserts'],
        correctIndex: 1,
        explanation: 'Steep slopes channel water very quickly into rivers, causing the water level to rise rapidly with little warning.'
      },
      {
        id: 'q14',
        question: 'What is the "Monsoon" that brings rain from May to October?',
        choices: ['Amihan (Northeast)', 'Habagat (Southwest)', 'Trade Winds', 'Easterlies'],
        correctIndex: 1,
        explanation: 'The Southwest Monsoon (Habagat) brings warm, moist air and heavy rains to the western part of the Philippines.'
      },
      {
        id: 'q15',
        question: 'Why are urban areas prone to flooding?',
        choices: ['More rain falls there', 'Concrete prevents water absorption', 'Too many people', 'Buildings are heavy'],
        correctIndex: 1,
        explanation: 'Impervious surfaces like asphalt and concrete prevent rain from soaking into the ground, increasing surface runoff.'
      },
      {
        id: 'q16',
        question: 'A "Yellow" rainfall warning means:',
        choices: ['Monitor the weather', 'Evacuate immediately', 'Alert/Standby', 'Go swimming'],
        correctIndex: 0,
        explanation: 'Yellow means "Monitor": heavy rain is falling, and flooding is possible in low-lying areas.'
      },
      {
        id: 'q17',
        question: 'What is "storm track"?',
        choices: ['The sound of thunder', 'The predicted path of the typhoon', 'A railway damaged by storm', 'The history of a storm'],
        correctIndex: 1,
        explanation: 'The storm track is the forecasted path the center of the cyclone will take.'
      },
      {
        id: 'q18',
        question: 'Which of these is a secondary hazard of typhoons?',
        choices: ['Volcanic eruption', 'Landslides', 'Drought', 'Heatwave'],
        correctIndex: 1,
        explanation: 'Heavy rainfall from typhoons saturates the soil, frequently triggering landslides in mountainous regions.'
      },
      {
        id: 'q19',
        question: 'What does "landfall" mean?',
        choices: ['The storm dies', 'The eye of the storm crosses the coastline', 'It starts raining', 'The wind stops'],
        correctIndex: 1,
        explanation: 'Landfall occurs when the center of the storm (the eye) moves over land.'
      },
      {
        id: 'q20',
        question: 'How do forests reduce flooding?',
        choices: ['They drink all the water', 'Roots absorb water and canopy slows rain impact', 'Trees block the river', 'They heat the air'],
        correctIndex: 1,
        explanation: 'Forests act as sponges. The canopy breaks the fall of rain, and the roots create porous soil that absorbs water.'
      }
    ]
  },
  {
    id: 'mod_vol',
    type: DisasterType.Volcano,
    title: 'Volcanic Eruption',
    description: 'Geothermal energy, ash chemistry, and lahar flows.',
    icon: '🌋',
    color: 'bg-red-600',
    learningContent: `### Geology: Types of Eruptions
* **Phreatic**: Steam-driven explosions caused by water heating up (e.g., Taal 2020 initial blast).
* **Magmatic**: Explosive release of gas and magma.
* **Plinian**: The most violent type, creating massive columns of gas and ash into the stratosphere (e.g., Pinatubo 1991).

### Volcanic Hazards
* **Pyroclastic Flow**: Superheated gas and rock racing down slopes at >80 kph. Impossible to outrun.
* **Lahar**: Volcanic mudflows. Rain mobilizes old ash deposits, creating concrete-like destruction.
* **Vog (Volcanic Smog)**: Sulfur dioxide (SO2) reacting with sunlight and moisture. Hazardous to lungs.

### Agriculture & Soil Science
While destructive initially, volcanic ash creates some of the most fertile soil on Earth (Andisols).
* **Nutrients**: Ash is rich in Potassium, Phosphorus, and trace minerals.
* **Acidity**: Fresh ash is often acidic and can "burn" plant leaves. Farmers must wash crops or wait for pH neutralization.

### Geothermal Energy
The Philippines is a top producer of geothermal energy. Heat from magma reservoirs is tapped to generate electricity (Tiwi, Mak-Ban, Leyte plants). This is the positive side of living in the Ring of Fire.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What is a "Phreatic" eruption?',
        choices: ['Magma-driven', 'Steam-driven', 'Lava flow only', 'Invisible eruption'],
        correctIndex: 1,
        explanation: 'Phreatic eruptions occur when groundwater is heated by magma, flashing to steam and causing an explosion without necessarily ejecting fresh magma.'
      },
      {
        id: 'q2',
        question: 'What is the most deadly hazard of a volcano, consisting of superheated gas and rocks?',
        choices: ['Lava flow', 'Pyroclastic Flow', 'Ashfall', 'Earthquake'],
        correctIndex: 1,
        explanation: 'Pyroclastic flows travel at high speeds and high temperatures, destroying everything in their path. You cannot outrun them.'
      },
      {
        id: 'q3',
        question: 'What is "Lahar"?',
        choices: ['Molten rock', 'Volcanic mudflow', 'Toxic gas', 'Volcanic lightning'],
        correctIndex: 1,
        explanation: 'Lahar is a flowing mixture of volcanic debris and water, often triggered by rain on loose ash deposits.'
      },
      {
        id: 'q4',
        question: 'Why is volcanic soil (Andisol) beneficial for agriculture in the long term?',
        choices: ['It kills all insects', 'It is rich in minerals like Potassium and Phosphorus', 'It is always wet', 'It prevents weeds'],
        correctIndex: 1,
        explanation: 'Weathered volcanic ash releases essential nutrients, making the soil highly fertile for crops like abaca, coconut, and vegetables.'
      },
      {
        id: 'q5',
        question: 'Which gas causes "Vog" and respiratory irritation?',
        choices: ['Oxygen', 'Sulfur Dioxide (SO2)', 'Helium', 'Nitrogen'],
        correctIndex: 1,
        explanation: 'SO2 reacts with atmospheric moisture to form acidic aerosols (Vog), which irritates the eyes, nose, and throat.'
      },
      {
        id: 'q6',
        question: 'What is the "Permanent Danger Zone" (PDZ)?',
        choices: ['An area where no one is allowed to live due to constant risk', 'An area for tourists', 'A safe zone', 'A mining zone'],
        correctIndex: 0,
        explanation: 'PDZ is a delineated area around a volcano (e.g., 6km for Mayon) declared permanently unsafe for habitation.'
      },
      {
        id: 'q7',
        question: 'Which Philippine volcano is known for having a "lake within a lake"?',
        choices: ['Mt. Mayon', 'Taal Volcano', 'Mt. Pinatubo', 'Mt. Kanlaon'],
        correctIndex: 1,
        explanation: 'Taal Volcano consists of an island in Taal Lake, which itself contains a crater lake (Main Crater Lake).'
      },
      {
        id: 'q8',
        question: 'What Alert Level indicates a hazardous eruption is imminent (hours/days)?',
        choices: ['Alert Level 1', 'Alert Level 3', 'Alert Level 4', 'Alert Level 5'],
        correctIndex: 2,
        explanation: 'Alert Level 4 means intense unrest and hazardous eruption is possible within days.'
      },
      {
        id: 'q9',
        question: 'How does a volcanic eruption affect global climate?',
        choices: ['It warms the Earth immediately', 'Ash and sulfur reflect sunlight, causing temporary cooling', 'It removes the ozone layer', 'It has no effect'],
        correctIndex: 1,
        explanation: 'Major eruptions (like Pinatubo) inject sulfur aerosols into the stratosphere, reflecting sunlight and cooling the global average temperature.'
      },
      {
        id: 'q10',
        question: 'What mask is best for fine volcanic ash?',
        choices: ['Surgical mask', 'N95 mask', 'Handkerchief', 'Face shield'],
        correctIndex: 1,
        explanation: 'N95 masks are designed to filter out 95% of airborne particles, including fine silica dust from ash.'
      },
      {
        id: 'q11',
        question: 'What is magma called once it reaches the surface?',
        choices: ['Lava', 'Rock', 'Slag', 'Basalt'],
        correctIndex: 0,
        explanation: 'Magma is underground; once it erupts onto the surface, it is called Lava.'
      },
      {
        id: 'q12',
        question: 'Which energy source is derived from volcanic heat?',
        choices: ['Solar', 'Hydroelectric', 'Geothermal', 'Nuclear'],
        correctIndex: 2,
        explanation: 'Geothermal energy taps into the heat reservoirs often found near volcanoes to generate electricity.'
      },
      {
        id: 'q13',
        question: 'What creates the lightning often seen in volcanic plumes?',
        choices: ['Thunderstorms', 'Static electricity from colliding ash particles', 'Aliens', 'Heat'],
        correctIndex: 1,
        explanation: 'Volcanic lightning is caused by the friction of ash particles rubbing together, generating static charge.'
      },
      {
        id: 'q14',
        question: 'Which volcano had the second largest eruption of the 20th century?',
        choices: ['Mt. St. Helens', 'Mt. Pinatubo', 'Krakatoa', 'Mt. Fuji'],
        correctIndex: 1,
        explanation: 'Mt. Pinatubo\'s 1991 eruption was the second largest of the century, cooling the earth by 0.5°C.'
      },
      {
        id: 'q15',
        question: 'What is a "Caldera"?',
        choices: ['A type of lava', 'A large depression formed when a volcano collapses into itself', 'A volcanic rock', 'A measuring tool'],
        correctIndex: 1,
        explanation: 'A caldera is a cauldron-like hollow that forms shortly after the emptying of a magma chamber in a volcanic eruption.'
      },
      {
        id: 'q16',
        question: 'If you are driving during heavy ashfall, what should you do?',
        choices: ['Speed up', 'Turn on headlights and drive slowly or stop', 'Use wipers constantly', 'Open windows'],
        correctIndex: 1,
        explanation: 'Ash drastically reduces visibility and makes roads slippery. Wipers can scratch the glass with ash.'
      },
      {
        id: 'q17',
        question: 'What is Viscosity?',
        choices: ['The temperature of lava', 'A fluid\'s resistance to flow (thickness)', 'The speed of eruption', 'The color of rock'],
        correctIndex: 1,
        explanation: 'High viscosity magma (thick/sticky) traps gas, leading to more explosive eruptions.'
      },
      {
        id: 'q18',
        question: 'Which rock floats in water?',
        choices: ['Granite', 'Pumice', 'Basalt', 'Limestone'],
        correctIndex: 1,
        explanation: 'Pumice is a volcanic rock full of gas bubbles, making it light enough to float.'
      },
      {
        id: 'q19',
        question: 'What is the "Ring of Fire"?',
        choices: ['A Johnny Cash song', 'A path along the Pacific Ocean characterized by active volcanoes and earthquakes', 'A forest fire pattern', 'A circus act'],
        correctIndex: 1,
        explanation: 'It is the circum-Pacific belt where most of the world\'s earthquakes and volcanic eruptions occur.'
      },
      {
        id: 'q20',
        question: 'How do you clean ash off a roof?',
        choices: ['Spray it with water immediately', 'Sweep it dry while wearing a mask', 'Leave it', 'Wait for rain'],
        correctIndex: 1,
        explanation: 'Ash becomes heavy cement-like sludge when wet. It\'s best to sweep it dry carefully to avoid collapsing the roof.'
      }
    ]
  },
  {
    id: 'mod_ls',
    type: DisasterType.Landslide,
    title: 'Landslide',
    description: 'Geomorphology, shear stress, and slope stabilization.',
    icon: '⛰️',
    color: 'bg-yellow-700',
    learningContent: `### Geomorphology: Why Slopes Fail
A landslide occurs when the **Shear Stress** (gravity pulling soil down) exceeds the **Shear Strength** (friction and cohesion holding it in place).
* **Triggers**: Heavy rain (increases weight, decreases friction), Earthquakes (shaking loosens bond), or Excavation (removing support).
* **Soil Saturation**: Water fills the gaps between soil particles (pore pressure), pushing them apart and turning the slope into a slurry.

### Warning Signs
* **Drunken Forests**: Trees tilting at odd angles.
* **Cracks**: New cracks in foundations, roads, or soil.
* **Springs**: New water seeps appearing on slopes.

### Mitigation & Agriculture
* **Coconut Trees**: Contrary to popular belief, coconut trees have shallow roots and do NOT hold soil well on steep slopes.
* **Vetiver Grass**: Specifically used for bio-engineering. Its roots grow 3-4 meters deep, acting like "living nails" to hold soil.
* **Terracing**: Ancient technique (like Banaue) to reduce slope angle and manage water runoff.`,
    quizItems: [
      {
        id: 'q1',
        question: 'What happens to soil physics when it becomes saturated with water?',
        choices: ['It becomes stronger', 'Pore water pressure increases, reducing friction', 'It becomes lighter', 'It turns into rock'],
        correctIndex: 1,
        explanation: 'Water lubricates the soil particles and pushes them apart (buoyancy), drastically reducing the friction that holds the slope together.'
      },
      {
        id: 'q2',
        question: 'What does the term "Drunken Forest" indicate?',
        choices: ['Trees fermenting fruit', 'Trees tilting due to slow ground movement (creep)', 'A forest with no leaves', 'Trees struck by lightning'],
        correctIndex: 1,
        explanation: 'Tilting trees indicate that the ground beneath them is slowly shifting or creeping downslope.'
      },
      {
        id: 'q3',
        question: 'Which plant is best for slope stabilization due to deep roots?',
        choices: ['Coconut Tree', 'Banana', 'Vetiver Grass', 'Corn'],
        correctIndex: 2,
        explanation: 'Vetiver grass has dense, massive root systems that penetrate deep into the soil, anchoring it effectively.'
      },
      {
        id: 'q4',
        question: 'What is the primary danger of "illegal logging" related to disasters?',
        choices: ['Loss of wood', 'Increased risk of landslides and flash floods', 'Hotter weather', 'Less fruit'],
        correctIndex: 1,
        explanation: 'Tree roots anchor soil and canopies slow down rain impact. Removing them destabilizes slopes and increases runoff.'
      },
      {
        id: 'q5',
        question: 'If caught in a landslide, what is the best defensive position?',
        choices: ['Run downhill', 'Curl into a tight ball and protect your head', 'Stand still', 'Climb a tree'],
        correctIndex: 1,
        explanation: 'If you cannot escape, curling into a ball offers the best protection for your vital organs against crushing debris.'
      },
      {
        id: 'q6',
        question: 'Which human activity often triggers landslides in the Philippines?',
        choices: ['Fishing', 'Road construction (cutting slopes)', 'Rice farming', 'Weaving'],
        correctIndex: 1,
        explanation: 'Cutting into the toe of a slope for roads or houses removes physical support, destabilizing the mass above.'
      },
      {
        id: 'q7',
        question: 'Which region is highly prone to landslides due to its mountainous terrain?',
        choices: ['NCR', 'CAR (Cordillera)', 'Central Luzon', 'Bicol'],
        correctIndex: 1,
        explanation: 'The Cordillera Administrative Region consists almost entirely of steep mountains, making it very susceptible to slope failures.'
      },
      {
        id: 'q8',
        question: 'What sound might precede a landslide?',
        choices: ['A high pitched whistle', 'A faint rumbling that gets louder', 'Sirens', 'Silence'],
        correctIndex: 1,
        explanation: 'As the earth moves and trees/rocks grind together, a low rumbling sound is often heard before the main slide.'
      },
      {
        id: 'q9',
        question: 'What is "Soil Creep"?',
        choices: ['A scary bug', 'The very slow, imperceptible downward movement of soil', 'A fast mudflow', 'Soil drying out'],
        correctIndex: 1,
        explanation: 'Creep is the slow deformation of slope material under gravity. It usually precedes more rapid failure.'
      },
      {
        id: 'q10',
        question: 'Why are mining areas prone to landslides?',
        choices: ['They use dynamite', 'Vegetation removal and soil loosening', 'Trucks are heavy', 'All of the above'],
        correctIndex: 3,
        explanation: 'Mining combines deforestation, excavation, vibrations, and waste piling, creating a perfect recipe for instability.'
      },
      {
        id: 'q11',
        question: 'What is "Shear Strength" in soil mechanics?',
        choices: ['The weight of the soil', 'The ability of soil to resist forces that cause it to slide', 'The water content', 'The color of soil'],
        correctIndex: 1,
        explanation: 'Shear strength comes from friction between particles and cohesion (stickiness).'
      },
      {
        id: 'q12',
        question: 'Why does "Terracing" help prevent landslides?',
        choices: ['It looks nice', 'It reduces the slope angle and slows water runoff', 'It removes soil', 'It adds weight'],
        correctIndex: 1,
        explanation: 'Terracing breaks a steep slope into a series of steps, reducing the speed of water flow and erosion.'
      },
      {
        id: 'q13',
        question: 'Which soil type is most prone to landslides?',
        choices: ['Solid rock', 'Loose, saturated soil or clay', 'Dry sand', 'Concrete'],
        correctIndex: 1,
        explanation: 'Loose soils, especially when wet (saturated clay), lose their strength easily.'
      },
      {
        id: 'q14',
        question: 'What is the "toe" of a slope?',
        choices: ['The top', 'The bottom or base', 'The middle', 'The back'],
        correctIndex: 1,
        explanation: 'The toe supports the weight of the slope above it. Excavating the toe is a common cause of landslides.'
      },
      {
        id: 'q15',
        question: 'How do roots help stable slopes?',
        choices: ['They drink water', 'They act as anchors and binders for the soil', 'They attract worms', 'They heat the ground'],
        correctIndex: 1,
        explanation: 'Roots provide mechanical reinforcement, acting like rebar in concrete.'
      }
    ]
  },
  {
    id: 'mod_ss',
    type: DisasterType.StormSurge,
    title: 'Storm Surge',
    description: 'Oceanography, bathymetry, and coastal defense.',
    icon: '🌊',
    color: 'bg-teal-600',
    learningContent: `### Oceanography: Mechanics of a Surge
A storm surge is NOT a tsunami. It is driven by wind.
* **Wind Setup**: Strong winds push water toward the shore.
* **Pressure Setup**: Low pressure in the eye of the storm allows the ocean surface to rise slightly (inverse barometer effect), though wind is the main driver.
* **Bathymetry**: Shallow, gently sloping continental shelves (like Leyte Gulf) allow water to pile up higher than deep, steep coasts.

### Astronomical Tide
If a surge happens during High Tide, the total water level (Storm Tide) is catastrophic. This is what happened during Typhoon Yolanda (Haiyan).

### Mangroves as Bioshields
Mangrove forests can reduce wave height by up to 66% over 100 meters.
* **Species**: Rhizophora (Bakawan) has prop roots that dissipate wave energy.
* **Ecosystem Services**: They also provide nurseries for fish (food security) and sequester carbon.`,
    quizItems: [
        {
        id: 'q1',
        question: 'Which factor contributes MOST to the height of a storm surge?',
        choices: ['Low pressure', 'Strong winds pushing water', 'Heavy rain', 'Earth rotation'],
        correctIndex: 1,
        explanation: 'While low pressure helps, the sheer force of wind piling water up against the coast is the dominant factor.'
      },
      {
        id: 'q2',
        question: 'What is "Bathymetry"?',
        choices: ['The study of bats', 'The measurement of depth of water in oceans', 'The temperature of the sea', 'The saltiness of water'],
        correctIndex: 1,
        explanation: 'Bathymetry refers to the underwater depth and shape of the ocean floor. Shallow, sloping floors amplify surges.'
      },
      {
        id: 'q3',
        question: 'Why was the Typhoon Yolanda surge so deadly in Tacloban?',
        choices: ['It was a tsunami', 'The funnel shape of Leyte Gulf trapped and amplified the water', 'There was no warning', 'It happened at night'],
        correctIndex: 1,
        explanation: 'The geography of Leyte Gulf funneled the water, forcing it to pile up higher as it moved into the narrower bay.'
      },
      {
        id: 'q4',
        question: 'How do mangroves help during storm surges?',
        choices: ['They stop the wind', 'Their dense roots dissipate wave energy and reduce flow speed', 'They absorb all the water', 'They scare the storm away'],
        correctIndex: 1,
        explanation: 'The complex root systems of mangroves act as a physical buffer, breaking the energy of incoming waves.'
      },
      {
        id: 'q5',
        question: 'What is the safest vertical evacuation point during a surge?',
        choices: ['The roof of a wooden house', 'The second floor or higher of a reinforced concrete building', 'A tall tree', 'Under the bed'],
        correctIndex: 1,
        explanation: 'You must be above the water level in a structure that can withstand the battering of waves and debris.'
      },
      {
        id: 'q6',
        question: 'What is the local term for storm surge introduced by PAGASA for better awareness?',
        choices: ['Daluyong', 'Tsunami', 'Baha', 'Alon'],
        correctIndex: 0,
        explanation: 'PAGASA promotes "Daluyong" to differentiate the violent ocean rise from normal flooding.'
      },
      {
        id: 'q7',
        question: 'Does a storm surge involve saltwater or freshwater?',
        choices: ['Freshwater', 'Saltwater', 'Both', 'Neither'],
        correctIndex: 1,
        explanation: 'It is an abnormal rise of the ocean, pushing saltwater inland, which causes corrosion and soil salination.'
      },
      {
        id: 'q8',
        question: 'When is a storm surge warning usually raised?',
        choices: ['After the storm passes', '24-48 hours before expected landfall', '1 hour before', 'Only when it rains'],
        correctIndex: 1,
        explanation: 'Warnings are issued ahead of landfall to give communities time to evacuate to higher ground.'
      },
      {
        id: 'q9',
        question: 'Which is safer during a storm surge: a beach resort or a hill 1km inland?',
        choices: ['Beach resort', 'Hill 1km inland', 'Both are safe', 'Neither'],
        correctIndex: 1,
        explanation: 'Distance from the coast and elevation are your best defenses against surges.'
      },
      {
        id: 'q10',
        question: 'What defines a "Storm Tide"?',
        choices: ['A detergent', 'The combination of Astronomical Tide + Storm Surge', 'A tide caused by rain', 'Low tide during a storm'],
        correctIndex: 1,
        explanation: 'Storm Tide is the actual level of water reached, combining the normal tide level with the surge rise.'
      },
      {
        id: 'q11',
        question: 'Why are convex coastlines less prone to high surges than concave (bay) coastlines?',
        choices: ['They are prettier', 'Water can disperse sideways instead of being trapped', 'They have more sand', 'They are deeper'],
        correctIndex: 1,
        explanation: 'Concave bays trap water, forcing it to pile up. Convex shapes allow water to flow around.'
      },
      {
        id: 'q12',
        question: 'What is the "Inverse Barometer Effect"?',
        choices: ['Measuring wind backwards', 'Sea level rises 1cm for every 1hPa drop in atmospheric pressure', 'Temperature drop', 'Wave crashing'],
        correctIndex: 1,
        explanation: 'Low pressure sucks the ocean surface up slightly, contributing to the surge.'
      },
      {
        id: 'q13',
        question: 'Can storm surges travel inland?',
        choices: ['No, they stop at the beach', 'Yes, sometimes kilometers inland depending on terrain', 'Only 1 meter', 'Only in rivers'],
        correctIndex: 1,
        explanation: 'In flat terrain, storm surges can penetrate several kilometers inland, destroying homes and crops.'
      },
      {
        id: 'q14',
        question: 'What distinguishes a storm surge from a tidal wave?',
        choices: ['Nothing', 'Storm surge is wind-driven; Tidal wave is gravitational', 'Storm surge is smaller', 'Tidal waves are blue'],
        correctIndex: 1,
        explanation: 'Tidal waves are caused by the moon/sun gravity. Surges are meteorological (weather-driven).'
      },
      {
        id: 'q15',
        question: 'What happens to soil after a storm surge recedes?',
        choices: ['It becomes very fertile', 'It becomes salinated (salty) and unfit for most crops', 'It disappears', 'It turns to rock'],
        correctIndex: 1,
        explanation: 'Saltwater intrusion damages soil structure and kills freshwater plants, requiring years to recover.'
      }
    ]
  },
  {
    id: 'mod_ind',
    type: DisasterType.Industrial,
    title: 'Industrial Hazards',
    description: 'Toxicology, chemical safety, and fire dynamics.',
    icon: '🏭',
    color: 'bg-gray-600',
    learningContent: `### Toxicology
* **Routes of Entry**: Inhalation (breathing), Absorption (skin), Ingestion (eating), Injection (cuts).
* **Acute vs Chronic**: Acute is immediate effect (e.g., acid burn). Chronic is long-term (e.g., asbestos causing cancer years later).

### Chemical Safety
* **GHS Symbols**: The Globally Harmonized System uses diamond symbols. 
    * *Flammable* (Fire)
    * *Corrosive* (Test tubes pouring on hand/metal)
    * *Health Hazard* (Person with star on chest - carcinogens).
* **SDS (Safety Data Sheet)**: The 16-section document that MUST be available for every chemical. It lists First Aid, Firefighting, and Handling.

### Fire Dynamics
* **Fire Triangle**: Fuel, Heat, Oxygen. Remove one to extinguish.
* **Classes of Fire**:
    * Class A: Solids (Wood/Paper) -> Use Water.
    * Class B: Liquids (Gas/Oil) -> Foam/CO2. Never use water (it spreads oil).
    * Class C: Electrical -> CO2/Dry Chem. Never use water (shock hazard).`,
    quizItems: [
        {
        id: 'q1',
        question: 'What does the GHS symbol of a "Silhouette of a person with a star on their chest" mean?',
        choices: ['Super hero', 'Health Hazard (Carcinogen/Mutagen)', 'Explosive', 'Radioactive'],
        correctIndex: 1,
        explanation: 'This symbol indicates serious long-term health hazards like cancer, respiratory sensitization, or reproductive toxicity.'
      },
      {
        id: 'q2',
        question: 'Why should you NEVER throw water on a grease/oil fire (Class B)?',
        choices: ['It will make the food taste bad', 'Oil floats on water, so the fire will spread and splash', 'Water is too cold', 'It will turn into ice'],
        correctIndex: 1,
        explanation: 'Water is denser than oil. The water sinks, boils instantly, and throws the burning oil into the air, creating a fireball.'
      },
      {
        id: 'q3',
        question: 'In the Fire Triangle, what are the three elements needed for fire?',
        choices: ['Wood, Match, Air', 'Fuel, Heat, Oxygen', 'Gas, Spark, Wind', 'Earth, Wind, Fire'],
        correctIndex: 1,
        explanation: 'Fire is a chemical reaction that requires Fuel, Heat, and Oxygen. Removing any one extinguishes the fire.'
      },
      {
        id: 'q4',
        question: 'What is the first thing you should look for before using a new chemical at work?',
        choices: ['The price tag', 'The SDS (Safety Data Sheet)', 'The smell', 'The color'],
        correctIndex: 1,
        explanation: 'The SDS contains critical safety info. You must read it to know the risks and required PPE.'
      },
      {
        id: 'q5',
        question: 'What is the acronym "PASS" for using a fire extinguisher?',
        choices: ['Pull, Aim, Squeeze, Sweep', 'Push, Aim, Shoot, Stop', 'Pull, Ask, Scream, Sprint', 'Put, Away, Safe, Sound'],
        correctIndex: 0,
        explanation: 'Pull the pin, Aim at the base of the fire, Squeeze the handle, Sweep side to side.'
      },
      {
        id: 'q6',
        question: 'Which route of entry involves chemicals entering through the skin?',
        choices: ['Inhalation', 'Ingestion', 'Absorption', 'Injection'],
        correctIndex: 2,
        explanation: 'Absorption occurs when chemicals pass through the skin barrier into the bloodstream.'
      },
      {
        id: 'q7',
        question: 'What is "Shelter in Place"?',
        choices: ['Building a fort', 'Staying indoors, closing windows/AC, and sealing gaps during a chemical release', 'Running to a shelter', 'Going to the basement'],
        correctIndex: 1,
        explanation: 'It creates a temporary barrier between you and the toxic air outside.'
      },
      {
        id: 'q8',
        question: 'What does an "Oxidizer" symbol mean?',
        choices: ['It releases oxygen and intensifies fires', 'It is breathable air', 'It rusts metal', 'It is water'],
        correctIndex: 0,
        explanation: 'Oxidizers provide oxygen to a fire, making it burn much hotter and faster, even without air.'
      },
      {
        id: 'q9',
        question: 'What gas is known as the "Silent Killer" produced by incomplete combustion?',
        choices: ['Carbon Dioxide', 'Carbon Monoxide', 'Nitrogen', 'Oxygen'],
        correctIndex: 1,
        explanation: 'Carbon Monoxide (CO) is colorless and odorless. It binds to hemoglobin in blood, preventing oxygen transport.'
      },
      {
        id: 'q10',
        question: 'What type of fire extinguisher is best for electrical fires (Class C)?',
        choices: ['Water', 'Carbon Dioxide (CO2)', 'Foam', 'Wet Chemical'],
        correctIndex: 1,
        explanation: 'CO2 is non-conductive and leaves no residue, making it safe for electrical equipment.'
      },
      {
        id: 'q11',
        question: 'What does "PPE" stand for?',
        choices: ['People Protection Equipment', 'Personal Protective Equipment', 'Public Place Entry', 'Paper Plastic Energy'],
        correctIndex: 1,
        explanation: 'PPE includes gloves, goggles, masks, and suits designed to protect the wearer from injury.'
      },
      {
        id: 'q12',
        question: 'If a chemical splashes in your eye, how long should you rinse it?',
        choices: ['5 seconds', 'At least 15-20 minutes', 'Just blink', 'Rub it'],
        correctIndex: 1,
        explanation: 'Long flushing is required to dilute and wash away the chemical completely to prevent permanent damage.'
      },
      {
        id: 'q13',
        question: 'What is "Flash Point"?',
        choices: ['The speed of light', 'The lowest temperature at which vapors ignite', 'A superhero', 'Boiling point'],
        correctIndex: 1,
        explanation: 'Flash point determines flammability. The lower the flash point, the easier it is to start a fire.'
      },
      {
        id: 'q14',
        question: 'What does the Skull and Crossbones symbol mean?',
        choices: ['Pirate zone', 'Acute Toxicity (Fatal or Toxic)', 'Bone doctor', 'Graveyard'],
        correctIndex: 1,
        explanation: 'It indicates substances that can cause death or severe toxicity in small amounts.'
      },
      {
        id: 'q15',
        question: 'What is the color of a flammability diamond in the NFPA 704 system?',
        choices: ['Blue', 'Red', 'Yellow', 'White'],
        correctIndex: 1,
        explanation: 'Red indicates flammability, Blue is health, Yellow is instability, and White is special hazard.'
      }
    ]
  },
  {
    id: 'mod_epi',
    type: DisasterType.Epidemic,
    title: 'Epidemics',
    description: 'Virology, immunology, and public health.',
    icon: '🦠',
    color: 'bg-green-600',
    learningContent: `### Biology: The Enemy
* **Virus**: A genetic code (DNA/RNA) inside a protein shell. It cannot reproduce on its own; it hijacks host cells. (e.g., Dengue, COVID-19).
* **Bacteria**: Single-celled organisms. Some are helpful, some cause disease (e.g., Leptospirosis). Treated with antibiotics.
* **Vector**: An organism (mosquito, rat) that transmits the pathogen.

### Immunology: Herd Immunity
When a high percentage of a population (e.g., 80-90%) is immune (via vaccination or prior infection), the virus cannot find new hosts to spread. This protects the vulnerable who cannot be vaccinated.

### Public Health: R0 (R-naught)
The reproduction number. It represents how many people one sick person will infect on average.
* If R0 > 1: The epidemic grows.
* If R0 < 1: The epidemic dies out.
* Interventions like masks, distancing, and vaccines aim to lower R0.

### Zoonosis
Diseases jumping from animals to humans (e.g., Rabies, Ebola, SARS-CoV-2). 75% of new infectious diseases are zoonotic, often linked to wildlife trade or habitat encroachment.`,
    quizItems: [
        {
        id: 'q1',
        question: 'What is "R-naught" (R0) in epidemiology?',
        choices: ['The number of recoveries', 'The basic reproduction number (how many people one case infects)', 'The death rate', 'The number of hospitals'],
        correctIndex: 1,
        explanation: 'R0 indicates the contagiousness of a pathogen. If R0 is 3, one person infects 3 others on average.'
      },
      {
        id: 'q2',
        question: 'What is the main difference between a Virus and Bacteria?',
        choices: ['Viruses are bigger', 'Bacteria need a host to reproduce, Viruses don\'t', 'Viruses require a living host to replicate; Bacteria can live independently', 'They are the same'],
        correctIndex: 2,
        explanation: 'Viruses are obligate parasites—they are practically inert until they enter a living cell.'
      },
      {
        id: 'q3',
        question: 'Which mosquito bites primarily during the day and carries Dengue?',
        choices: ['Anopheles', 'Aedes aegypti', 'Culex', 'House Fly'],
        correctIndex: 1,
        explanation: 'Aedes aegypti is the "day-biting" mosquito, easily recognized by white markings on its legs.'
      },
      {
        id: 'q4',
        question: 'How do vaccines work?',
        choices: ['They cure the disease', 'They train the immune system to recognize the pathogen without making you sick', 'They make you superhuman', 'They kill all bacteria'],
        correctIndex: 1,
        explanation: 'Vaccines present a harmless part of the pathogen (antigen) to the body, creating memory cells for future defense.'
      },
      {
        id: 'q5',
        question: 'What is "Zoonosis"?',
        choices: ['A zoo disease', 'A disease transmitted from animals to humans', 'A fear of animals', 'Animal hospital'],
        correctIndex: 1,
        explanation: 'Zoonotic diseases (like Rabies or Leptospirosis) jump the species barrier from animals to humans.'
      },
      {
        id: 'q6',
        question: 'What is the 4S strategy against Dengue?',
        choices: ['Sleep, Swim, Sun, Sand', 'Search & destroy, Secure protection, Seek consultation, Support fogging', 'Soap, Scrub, Sanitizer, Shower', 'Stop, Shake, Shout, Slide'],
        correctIndex: 1,
        explanation: 'The DOH 4S strategy focuses on prevention (breeding sites) and early action.'
      },
      {
        id: 'q7',
        question: 'Antibiotics are effective against which type of pathogen?',
        choices: ['Viruses (Flu)', 'Bacteria', 'Fungi', 'All of the above'],
        correctIndex: 1,
        explanation: 'Antibiotics kill bacteria. They are useless against viruses like the Cold, Flu, or Dengue.'
      },
      {
        id: 'q8',
        question: 'What is the primary transmission mode of Leptospirosis during floods?',
        choices: ['Mosquito bites', 'Contact with rat urine through skin cuts/eyes', 'Eating dirty food', 'Coughing'],
        correctIndex: 1,
        explanation: 'Leptospira bacteria in animal urine contaminate floodwaters and enter the body through breaks in the skin.'
      },
      {
        id: 'q9',
        question: 'What is "Herd Immunity"?',
        choices: ['Cows being safe', 'Community protection achieved when a high % is immune', 'Immunity from drinking milk', 'Natural selection'],
        correctIndex: 1,
        explanation: 'When enough people are immune, the virus hits "dead ends" and stops spreading, protecting those who aren\'t immune.'
      },
      {
        id: 'q10',
        question: 'Why is handwashing with soap effective against viruses like Coronavirus?',
        choices: ['The soap is hot', 'The soap molecules break apart the virus\'s lipid (fatty) outer shell', 'It makes hands slippery', 'It drowns the virus'],
        correctIndex: 1,
        explanation: 'Soap is an amphiphile; it pries apart the fatty layer holding the virus together, effectively destroying it.'
      },
      {
        id: 'q11',
        question: 'What is the "incubation period"?',
        choices: ['Time to hatch eggs', 'Time between exposure to the virus and symptom onset', 'Time spent in hospital', 'Time to recover'],
        correctIndex: 1,
        explanation: 'Incubation is the silent period where the pathogen replicates before you feel sick.'
      },
      {
        id: 'q12',
        question: 'What does "Pandemic" mean?',
        choices: ['A disease in a pan', 'An epidemic that has spread over multiple countries or continents', 'A mild sickness', 'A local outbreak'],
        correctIndex: 1,
        explanation: 'Pandemic refers to the geographic spread, not necessarily severity. It means it is global.'
      },
      {
        id: 'q13',
        question: 'Rabies is 100% fatal once symptoms appear. How is it prevented after a bite?',
        choices: ['Drinking water', 'Post-exposure prophylaxis (PEP) vaccine immediately', 'Sleep', 'Herbal medicine'],
        correctIndex: 1,
        explanation: 'Immediate vaccination (PEP) stops the virus from reaching the brain. Once it does, there is no cure.'
      },
      {
        id: 'q14',
        question: 'What is "Asymptomatic"?',
        choices: ['Very sick', 'Infected but showing no symptoms', 'Cured', 'Immune'],
        correctIndex: 1,
        explanation: 'Asymptomatic carriers can spread disease without knowing they are sick, making control difficult.'
      },
      {
        id: 'q15',
        question: 'Which is an example of a "Vector-borne" disease?',
        choices: ['Malaria', 'Diabetes', 'Cancer', 'Asthma'],
        correctIndex: 0,
        explanation: 'Malaria is transmitted by the Anopheles mosquito vector.'
      }
    ]
  }
];

export const ACHIEVEMENTS: Achievement[] = [
    { 
        id: 'ach_reader', title: 'Curious Mind', description: 'Read 3 Learning Modules', icon: '📚', 
        requirement: (s, p) => s.modulesRead.length >= 3, rewardType: 'avatar', rewardValue: 'av_scout' 
    },
    { 
        id: 'ach_scholar', title: 'Walking Encyclopedia', description: 'Read ALL Learning Modules', icon: '🎓', 
        requirement: (s, p) => s.modulesRead.length >= MODULES.length, rewardType: 'avatar', rewardValue: 'av_nerd' 
    },
    { 
        id: 'ach_winner', title: 'Survivor', description: 'Win 5 Quizzes', icon: '🏆', 
        requirement: (s, p) => s.quizzesWon >= 5, rewardType: 'avatar', rewardValue: 'av_brain' 
    },
    { 
        id: 'ach_speed', title: 'Quick Reflexes', description: 'Average answer time under 5 seconds (min 10 qs)', icon: '⚡', 
        requirement: (s, p) => s.questionsAnswered > 10 && (s.totalAnswerTime / s.questionsAnswered) <= 5, rewardType: 'avatar', rewardValue: 'av_flash' 
    },
    { 
        id: 'ach_dedication', title: 'Dedicated', description: 'Play for 1 hour total', icon: '⏳', 
        requirement: (s, p) => s.totalSecondsPlayed >= 3600, rewardType: 'xp', rewardValue: 500 
    },
    { 
        id: 'ach_streak', title: 'Consistent', description: 'Reach a 7-day login streak', icon: '🔥', 
        requirement: (s, p) => p.dailyStreak >= 7, rewardType: 'border', rewardValue: 'bd_fire' 
    }
];

export const PH_REGIONS: RegionData[] = [
    { 
        id: 'NCR', 
        name: 'NCR (Metro Manila)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Typhoon, DisasterType.Epidemic], 
        info: '• **Seismic Risk**: The West Valley Fault runs directly through Marikina, Pasig, and Taguig. A M7.2 earthquake could cause severe structural damage. \n• **Urban Flooding**: High concrete coverage prevents water absorption, leading to rapid street flooding. \n• **Density**: 13M+ population makes it a hotspot for viral transmission.' 
    },
    { 
        id: 'CAR', 
        name: 'CAR (Cordillera)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Landslide], 
        info: '• **Topography**: Steep slopes (>50 degrees) are highly unstable during rain. \n• **Hazards**: Halsema Highway is frequently blocked by rockslides. \n• **Agriculture**: Frost damage ("Andap") affects vegetable crops in Benguet during cold months.' 
    },
    { 
        id: 'R1', 
        name: 'Region I (Ilocos)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Earthquake], 
        info: '• **Coastal**: Faces the West Philippine Sea, prone to storm surges. \n• **Seismic**: The Manila Trench offshore poses a tsunami threat. \n• **Agriculture**: Tobacco and garlic crops are vulnerable to excess moisture.' 
    },
    { 
        id: 'R2', 
        name: 'Region II (Cagayan Valley)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.StormSurge], 
        info: '• **Catchment Basin**: The Cagayan River drains water from multiple mountain ranges, causing massive floods (e.g., Ulysses 2020). \n• **Agriculture**: Major corn and rice producer; floods cause billions in losses.' 
    },
    { 
        id: 'R3', 
        name: 'Region III (Central Luzon)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Lahar**: Rain mobilizes old ash deposits from Mt. Pinatubo, clogging river channels. \n• **Food Security**: Known as the "Rice Granary"; typhoons here impact national rice supply.' 
    },
    { 
        id: 'R4A', 
        name: 'Region IV-A (Calabarzon)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Volcano, DisasterType.Earthquake], 
        info: '• **Taal Volcano**: Proximity to the Permanent Danger Zone involves Batangas and Cavite. \n• **Industrial**: High concentration of factories increases chemical hazard risks during earthquakes.' 
    },
    { 
        id: 'R4B', 
        name: 'Region IV-B (Mimaropa)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Landslide], 
        info: '• **Island Hazards**: Oriental Mindoro is prone to flooding; Palawan faces fewer typhoons but has landslide risks in mining areas. \n• **Maritime**: Inter-island travel is frequently suspended during gales.' 
    },
    { 
        id: 'R5', 
        name: 'Region V (Bicol)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Typhoon Pathway**: The first point of contact for many Pacific typhoons. \n• **Volcanism**: Mt. Mayon and Mt. Bulusan are active. Ashfall affects abaca and coconut crops.' 
    },
    { 
        id: 'R6', 
        name: 'Region VI (Western Visayas)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Volcano], 
        info: '• **Mt. Kanlaon**: Active volcano on Negros island. \n• **Oil Spill Risk**: Guimaras Strait is a busy shipping lane (e.g., 2006 Solar 1 spill). \n• **Agriculture**: Sugar cane fields are susceptible to wind damage.' 
    },
    { 
        id: 'R7', 
        name: 'Region VII (Central Visayas)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Landslide], 
        info: '• **Bohol Fault**: Source of the 2013 M7.2 Earthquake. \n• **Landslides**: Cebu\'s transcentral highway has steep, limestone slopes prone to slides. \n• **Urban**: Metro Cebu faces severe drainage issues.' 
    },
    { 
        id: 'R8', 
        name: 'Region VIII (Eastern Visayas)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.StormSurge], 
        info: '• **Surge Risk**: Leyte Gulf\'s shape amplifies storm surges (e.g., Yolanda). \n• **Tectonics**: The Philippine Trench runs parallel to the coast, posing high seismic risk.' 
    },
    { 
        id: 'R9', 
        name: 'Region IX (Zamboanga)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.StormSurge, DisasterType.Earthquake], 
        info: '• **Tsunami History**: The 1976 Moro Gulf earthquake caused a devastating tsunami here. \n• **Flooding**: Zamboanga City lowlands are prone to flash floods.' 
    },
    { 
        id: 'R10', 
        name: 'Region X (Northern Mindanao)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Typhoon], 
        info: '• **Flash Floods**: Deforestation in uplands exacerbates runoff, as seen in TS Sendong (2011) in Cagayan de Oro and Iligan.' 
    },
    { 
        id: 'R11', 
        name: 'Region XI (Davao)', 
        riskLevel: 'Medium', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Landslide], 
        info: '• **Seismic Swarms**: Series of strong quakes occurred in 2019. \n• **Mining**: Compostela Valley (Davao de Oro) has very high landslide susceptibility due to mining tunnels.' 
    },
    { 
        id: 'R12', 
        name: 'Region XII (Soccsksargen)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Typhoon], 
        info: '• **Cotabato Trench**: A major subduction zone. \n• **Flood Plains**: The Ligawasan Marsh can overflow, affecting North Cotabato and Maguindanao areas.' 
    },
    { 
        id: 'R13', 
        name: 'Region XIII (Caraga)', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Typhoon, DisasterType.Landslide], 
        info: '• **Mining Capital**: Surigao del Norte/Sur has extensive nickel mining, loosening soil. \n• **Deep Trench**: Proximity to the Philippine Trench makes it a seismic hotspot.' 
    },
    { 
        id: 'BARMM', 
        name: 'BARMM', 
        riskLevel: 'High', 
        commonHazards: [DisasterType.Earthquake, DisasterType.Epidemic], 
        info: '• **Complex Emergency**: Conflict often hampers disaster response and aid delivery. \n• **Tsunami**: The Celebes Sea poses a threat to coastal communities in Sulu and Tawi-Tawi.' 
    }
];